### ISSUE TITLE
Home page github link error

### ISSUE THREAD

**Issue by chgao96** [hugocarreira/jekyll-materializecss#4]
On the demo page http://hugocarreira.github.io/jekyll-materializecss, when I click the "Github" button, it is directed to http://hugocarreira.github.io/jekyll-materializecss/http://github.com/hugocarreira. Obvious it is wrong.

After all,  thanks for sharing this theme. I love material design!

**Comment by hugocarreira** [comment]
Fixed !

Thanks :)
